### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vlad99964** [darkphoenix/tolino-calibre-python#10]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\debug.py", line 314, in main
  File "calibre\debug.py", line 215, in run_script
  File "polyglot\builtins.py", line 110, in exec_path
  File "F:\Загрузки\tolino-calibre-sync-master\tolino-calibre-sync.py", line 83, in <module>
    conf = dict(confparse.items('Defaults'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "configparser.py", line 865, in items
configparser.NoSectionError: No section: 'Defaults'

**Comment by Nevio024** [comment]
Same error here :/

Loved the idea of this project so much!
